# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170512_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
